# Generated by Django 4.2.6 on 2023-10-19 09:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("aGit2Git", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="url",
            options={"ordering": ("name", "branch"), "verbose_name_plural": "Url"},
        ),
        migrations.AddField(
            model_name="url",
            name="branch",
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterUniqueTogether(
            name="url",
            unique_together={("name", "branch")},
        ),
        migrations.AddIndex(
            model_name="url",
            index=models.Index(fields=["name", "branch"], name="aGit2Git_ur_name_2ecfac_idx"),
        ),
    ]
