# Generated by Django 4.2.6 on 2023-10-19 09:29

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("aGit2Git", "0003_script_copytype_script"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="copytype",
            name="scriptName",
        ),
    ]
