# Generated by Django 5.2.2 on 2025-07-24 14:00

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("aGit2Git", "0006_feature_component"),
    ]

    operations = [
        migrations.CreateModel(
            name="Implementation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("creStamp", models.DateTimeField(auto_now_add=True)),
                ("updStamp", models.DateTimeField(auto_now=True, null=True)),
                ("implemented", models.BooleanField(default=True)),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "component",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="aGit2Git.component",
                    ),
                ),
                (
                    "feature",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="aGit2Git.feature",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Implementation",
                "ordering": ("component", "feature"),
                "indexes": [
                    models.Index(
                        fields=["implemented", "feature"],
                        name="aGit2Git_im_impleme_879434_idx",
                    ),
                    models.Index(
                        fields=["component", "feature"],
                        name="aGit2Git_im_compone_897f98_idx",
                    ),
                    models.Index(
                        fields=["feature", "component"],
                        name="aGit2Git_im_feature_660430_idx",
                    ),
                ],
                "unique_together": {("component", "feature")},
            },
        ),
    ]
