# Generated by Django 5.2.2 on 2025-07-25 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("aGit2Git", "0007_implementation"),
    ]

    operations = [
        migrations.AlterField(
            model_name="implementation",
            name="implemented",
            field=models.BooleanField(default=False),
        ),
    ]
