# Generated by Django 5.2.4 on 2025-07-29 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("aGit2Git", "0008_alter_implementation_implemented"),
    ]

    operations = [
        migrations.AddField(
            model_name="implementation",
            name="requested",
            field=models.BooleanField(default=False),
        ),
        migrations.AddIndex(
            model_name="implementation",
            index=models.Index(fields=["requested", "feature"], name="aGit2Git_im_request_226743_idx"),
        ),
    ]
