# Generated by Django 5.2.4 on 2025-07-29 11:31

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("aGit2Git", "0009_implementation_requested_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Dependencies",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("creStamp", models.DateTimeField(auto_now_add=True)),
                ("updStamp", models.DateTimeField(auto_now=True, null=True)),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "component",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user",
                        to="aGit2Git.component",
                    ),
                ),
                (
                    "uses",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="used",
                        to="aGit2Git.component",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Dependencies",
                "ordering": ("component", "uses"),
                "indexes": [
                    models.Index(
                        fields=["component", "uses"],
                        name="aGit2Git_de_compone_775779_idx",
                    ),
                    models.Index(
                        fields=["uses", "component"],
                        name="aGit2Git_de_uses_id_b4f6db_idx",
                    ),
                ],
                "unique_together": {("component", "uses")},
            },
        ),
    ]
