# Generated by Django 5.2.4 on 2025-07-29 12:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies: list = [
        ("aGit2Git", "0010_dependencies"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Url",
            new_name="Repo",
        ),
        migrations.RenameModel(
            old_name="UrlPair",
            new_name="RepoPair",
        ),
        migrations.AlterModelOptions(
            name="repo",
            options={"ordering": ("name", "branch"), "verbose_name_plural": "Repo"},
        ),
        migrations.AlterModelOptions(
            name="repopair",
            options={"ordering": ("name",), "verbose_name_plural": "RepoPair"},
        ),
        migrations.RenameIndex(
            model_name="repo",
            new_name="aGit2Git_re_name_a9c485_idx",
            old_name="aGit2Git_ur_name_2ecfac_idx",
        ),
    ]
