# Generated by Django 6.1.2 on 2026-10-09 18:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("aGit2Git", "0012_check_data_for_constraints"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Tag",
        ),
        migrations.AlterModelOptions(
            name="component",
            options={"ordering": ("name",), "verbose_name_plural": "components"},
        ),
        migrations.AlterModelOptions(
            name="copytype",
            options={"ordering": ("name",), "verbose_name_plural": "copy types"},
        ),
        migrations.AlterModelOptions(
            name="dependencies",
            options={
                "ordering": ("component", "uses"),
                "verbose_name": "dependency",
                "verbose_name_plural": "dependencies",
            },
        ),
        migrations.AlterModelOptions(
            name="feature",
            options={"ordering": ("name",), "verbose_name_plural": "features"},
        ),
        migrations.AlterModelOptions(
            name="implementation",
            options={"ordering": ("component", "feature"), "verbose_name_plural": "implementations"},
        ),
        migrations.AlterModelOptions(
            name="repo",
            options={"ordering": ("name", "branch"), "verbose_name_plural": "repos"},
        ),
        migrations.AlterModelOptions(
            name="repopair",
            options={"ordering": ("name",), "verbose_name_plural": "repo pairs"},
        ),
        migrations.AlterModelOptions(
            name="script",
            options={"ordering": ("name",), "verbose_name_plural": "scripts"},
        ),
        migrations.AlterModelOptions(
            name="server",
            options={"ordering": ("name",), "verbose_name_plural": "servers"},
        ),
        migrations.RemoveIndex(
            model_name="dependencies",
            name="aGit2Git_de_compone_775779_idx",
        ),
        migrations.RemoveIndex(
            model_name="implementation",
            name="aGit2Git_im_compone_897f98_idx",
        ),
        migrations.AlterUniqueTogether(
            name="dependencies",
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name="implementation",
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name="repo",
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name="dependencies",
            name="component",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="dependencies", to="aGit2Git.component"
            ),
        ),
        migrations.AlterField(
            model_name="dependencies",
            name="uses",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="used_by", to="aGit2Git.component"
            ),
        ),
        migrations.AlterField(
            model_name="repo",
            name="name",
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name="repo",
            name="server",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="repos", to="aGit2Git.server"
            ),
        ),
        migrations.AlterField(
            model_name="repo",
            name="url",
            field=models.URLField(max_length=255),
        ),
        migrations.AlterField(
            model_name="repopair",
            name="source",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="pairs_as_source", to="aGit2Git.repo"
            ),
        ),
        migrations.AlterField(
            model_name="repopair",
            name="target",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="pairs_as_target", to="aGit2Git.repo"
            ),
        ),
        migrations.AddConstraint(
            model_name="dependencies",
            constraint=models.UniqueConstraint(fields=("component", "uses"), name="dependencies_unique_component_uses"),
        ),
        migrations.AddConstraint(
            model_name="dependencies",
            constraint=models.CheckConstraint(
                condition=models.Q(("component", models.F("uses")), _negated=True),
                name="dependencies_not_self",
                violation_error_message="A component cannot depend on itself.",
            ),
        ),
        migrations.AddConstraint(
            model_name="implementation",
            constraint=models.UniqueConstraint(
                fields=("component", "feature"), name="implementation_unique_component_feature"
            ),
        ),
        migrations.AddConstraint(
            model_name="repo",
            constraint=models.UniqueConstraint(
                fields=("url", "branch"),
                name="repo_unique_url_branch",
                nulls_distinct=False,
                violation_error_message="This url already exists with the same branch.",
            ),
        ),
        migrations.AddConstraint(
            model_name="repopair",
            constraint=models.CheckConstraint(
                condition=models.Q(("source", models.F("target")), _negated=True),
                name="repopair_source_not_target",
                violation_error_message="Source and target must be different repos.",
            ),
        ),
    ]
